return {
 ["author"]="Petra Janouchová",
 ["htmlfiles"]={ "disproduct-div.xhtml" },
 ["htmlroot"]="disproduct-div.xhtml",
 ["identifier"]="d4e18ddf-49fb-8d7d-75a1-28e26a36838a",
 ["imagefile"]="styles/disproduct-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="cs",
 ["name"]="disproduct",
 ["stylepath"]="styles",
 ["styles"]={ "disproduct-defaults.css", "disproduct-images.css", "disproduct-styles.css" },
 ["subtitle"]="Hellenisation of Ancient Thrace based on epigraphical evidence",
 ["title"]="Hellénizace antické Thrákie ve světle epigrafických nálezů",
 ["xhtmlfiles"]={ "disproduct-tag.xhtml" },
 ["xmlfiles"]={ "disproduct-raw.xml" },
}