return {
 ["author"]="Mgr. Petra Janouchová",
 ["htmlfiles"]={ "disproduct-div.xhtml" },
 ["htmlroot"]="disproduct-div.xhtml",
 ["identifier"]="35980424-4c2b-8aca-a041-b0feb3dd8c1e",
 ["imagefile"]="styles/disproduct-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="cs",
 ["name"]="disproduct",
 ["stylepath"]="styles",
 ["styles"]={ "disproduct-defaults.css", "disproduct-images.css", "disproduct-styles.css" },
 ["subtitle"]="Hellenisation of Ancient Thrace based on epigraphical evidence",
 ["title"]="Hellénizace antické Thrákie ve světle epigrafických nálezů",
 ["xhtmlfiles"]={ "disproduct-tag.xhtml" },
 ["xmlfiles"]={ "disproduct-raw.xml" },
}